### ISSUE TITLE
scrum

### ISSUE THREAD

**Issue by Exequiel2k** [Exequiel2k/ispc-practica#10]
Crear Documento de Scrum

**Comment by Yanitoso** [comment]
Definición de Scrum:
Es un marco de trabajo a través del cual las personas pueden abordar problemas complejos adaptativos, a la vez que se entregan productos de forma eficiente y creativa con el máximo valor.

● Es un enfoque ágil para la gestión de un proyecto.
● Más que una metodología o proceso, es un Marco de Trabajo.
● Utiliza procesos interactivos/incrementales.
● Orientado a resultados y compromisos.
● No está restringido a proyectos de software solamente.
● Su visión es opuesta a la propuesta por la metodología en
cascada.

Pilares de Scrum:
Transparencia
Los aspectos significativos del proceso deben ser visibles para todos aquellos que son responsables del resultado. La transparencia requiere que dichos aspectos sean definidos en base a un estándar común, de tal modo que los observados compartan un entendimiento común de lo que se están viendo. Por ejemplo
• Deben compartir un lenguaje común a todos los participantes para referirse al proceso; y, • Aquellos que desempeñaron el trabajo y quienes inspeccionaron el incremento deben compartir una definición común de “Terminado” (“Done”).
inspección
Los usuarios de Scrum deben inspeccionar frecuentemente los Artefactos de Scrum y el progreso hacia un objetivo para detectar variaciones indeseadas. Su inspección no debe ser tan frecuente como para que pueda interferir en el trabajo. Las inspecciones son más beneficiosas cuando se realizan de forma diligente por inspectores expertos en el mismo lugar de trabajo.
Adaptación
Si un inspector determina que uno o más aspectos de un proceso se desvían de los límites aceptables y que el producto resultante será inaceptable, el proceso o el material que está siendo procesado deben ajustarse. Dicho ajuste deberá realizarse cuanto antes para minimizar las desviaciones mayores.
